name: vale
on:
  pull_request:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Vale
        uses: errata-ai/vale-action@v2
        with:
          version: 3.7.1
          files: docs/**/*.md README.md STYLE_GUIDE.md
