name: vale
on:
  pull_request:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Vale
        uses: errata-ai/vale-action@v2
        with:
          version: 3.7.1
          files: docs README.md STYLE_GUIDE.md
          reporter: github-check
          level: warning
          fail_on_error: true
          filter_mode: nofilter
